### ISSUE TITLE
Shader errors in TriPlanar and WorldSpaceshader on metal

### ISSUE THREAD

**Issue by strudgian** [ogoguel/EnterTheMatrix#1]
"Shader error in 'TriPlanar': undeclared identifier '_ColorMask' at line 110 (on metal)

"Shader error in 'WorldSpaceshader': undeclared identifier 'wp' at line 61(on metal)

"Shader error in 'WorldSpaceshader': 'frag': Not all control paths return a value at line 58 (on metal)

**Comment by ogoguel** [comment]
Thanks for the feedback : fixed

**Comment by strudgian** [comment]
You are welcome! Thank YOU for responding with a fix :)
